---
- name: Playbook that sends HTTP GET to target URI
  hosts: localhost

  vars:
    urltolookup: "https://pokeapi.co/api/v2/pokemon/pikachu"

  tasks:
  - name: Lookup API with uri module
    uri:
      url: "{{ urltolookup }}"
      method: GET
    register: results    # save the JSON sent back by our script

  - name: Print out the 'results'
    debug:
      var: results

